version: 2.1

jobs:
  hello-job:
    docker:
      - image: cimg/node:17.2.0 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
 #     - run: sleep 30 
 #     - run: exit 1
 #     - run: echo $CIRCLE_PULL_REQUEST
 #     - run: echo $CIRCLE_REPOSITORY_URL
 #     - run: echo "This is pipeline ID << pipeline.id >>"
 #     - run: echo "This is base revision << pipeline.git.base_revision >>" 
 #     - run: echo << pipeline.trigger_parameters.github_app.repo_url >>  
      - jq/install
      - run: echo << pipeline.trigger_parameters.webhook.body >> | jq .branch

workflows: 
  ghApp: 
    jobs: 
      - hello-job    
